// lib/fetcher/subcategory-embed.ts
// ---------------------------------------------------------------------
// Phase 2-A: embedding-based subcategory classification for cyber news.
//
// Approach: prototype vectors. Instead of hand-labelling a training set,
// we embed a small curated set of representative phrases ("prototypes")
// for each subcategory, average them into one reference vector per label,
// and store those in D1 (rag_config-style table). At classification time
// we embed the article and take cosine similarity to each reference; any
// label clearing the threshold is assigned (multi-label).
//
// This is deliberately simple and tunable. The keyword classifier in
// classifier.ts remains the deterministic fallback (and can be OR-ed with
// this for recall on explicit terms like "CVE-2025-…").
//
// The reference vectors are (re)generated by POST /api/subcategory-refs.
// ---------------------------------------------------------------------

import type { Env } from "../types";
import type { RagConfig } from "../rag/config";
import { embed, embedBatch } from "../rag/embeddings";

/** Subcategory labels we compute reference vectors for. "other" is the
 *  implicit fallback when nothing clears the threshold. */
export const SUBCATEGORY_LABELS = ["vulnerability", "incident"] as const;
export type SubLabel = typeof SUBCATEGORY_LABELS[number];

/**
 * Prototype phrases per subcategory. Bilingual on purpose so the
 * reference vectors sit sensibly for both English and Japanese sources
 * (the i18n verification goal). Keep these representative, not
 * exhaustive — a handful of clear exemplars per label works well.
 */
export const SUBCATEGORY_PROTOTYPES: Record<SubLabel, string[]> = {
  vulnerability: [
    "A critical vulnerability (CVE) was disclosed in the software, allowing remote code execution.",
    "Security researchers published a proof-of-concept exploit for a zero-day flaw.",
    "The vendor released a security patch and advisory to fix the vulnerability.",
    "A buffer overflow / SQL injection / XSS weakness was found in the product.",
    "JVN and the vendor issued a security update addressing multiple flaws.",
    "製品に深刻な脆弱性（CVE）が発見され、リモートコード実行が可能となる。",
    "ベンダーが脆弱性を修正するセキュリティパッチとアドバイザリを公開した。",
    "ゼロデイ脆弱性の実証コード（PoC）が公開された。",
  ],
  incident: [
    "A company suffered a data breach and customer information was leaked.",
    "A ransomware gang added a new victim to its leak site and demanded extortion.",
    "Attackers gained unauthorized access and exfiltrated sensitive data.",
    "The organization was hacked; the incident disrupted operations.",
    "Law enforcement announced a takedown and arrests targeting the threat actor.",
    "企業がランサムウェア被害に遭い、情報漏洩が発生した。",
    "攻撃者が不正アクセスによりデータを窃取した。",
    "ランサムウェアグループがリークサイトに新たな被害者を掲載した。",
  ],
};

const REF_KEY_PREFIX = "subref:"; // rag_config key namespace for references

/**
 * Generate reference vectors from the prototypes and persist them to D1
 * (rag_config table, one row per label as JSON). Returns the dimensions
 * used, for a sanity check against the embedding model.
 */
export async function generateSubcategoryRefs(
  env: Env,
  cfg: RagConfig,
): Promise<{ label: SubLabel; dims: number }[]> {
  const out: { label: SubLabel; dims: number }[] = [];

  for (const label of SUBCATEGORY_LABELS) {
    const vectors = await embedBatch(env, SUBCATEGORY_PROTOTYPES[label], cfg);
    if (!vectors.length) continue;
    const ref = averageVectors(vectors);
    const normalized = normalize(ref);
    await env.DB.prepare(
      `INSERT INTO rag_config (key, value, updated_at)
       VALUES (?, ?, CURRENT_TIMESTAMP)
       ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP`
    ).bind(REF_KEY_PREFIX + label, JSON.stringify(normalized)).run();
    out.push({ label, dims: normalized.length });
  }

  return out;
}

/** Load stored reference vectors. Returns null when none are present yet. */
export async function loadSubcategoryRefs(
  env: Env,
): Promise<Record<SubLabel, number[]> | null> {
  const res = await env.DB.prepare(
    `SELECT key, value FROM rag_config WHERE key LIKE ?`
  ).bind(REF_KEY_PREFIX + "%").all();

  const map: Partial<Record<SubLabel, number[]>> = {};
  for (const r of res.results ?? []) {
    const row = r as { key: string; value: string };
    const label = row.key.slice(REF_KEY_PREFIX.length) as SubLabel;
    if ((SUBCATEGORY_LABELS as readonly string[]).includes(label)) {
      try { map[label] = JSON.parse(row.value) as number[]; } catch { /* skip */ }
    }
  }

  const complete = SUBCATEGORY_LABELS.every(l => Array.isArray(map[l]) && map[l]!.length);
  return complete ? (map as Record<SubLabel, number[]>) : null;
}

/**
 * Classify the subcategory for a cyber article by embedding similarity.
 * Returns the SINGLE best-matching label (highest cosine similarity) as long
 * as it clears `threshold`; otherwise []. Single-label because vulnerability
 * and incident overlap heavily in wording (e.g. a "情報漏えいに関する脆弱性"
 * JVN advisory scores high on both) — multi-label was tagging plain
 * vulnerability advisories as incidents too, so they leaked into the Incident
 * tab. Picking the dominant label keeps each article in one bucket; a genuine
 * vuln advisory lands in vulnerability (its stronger match), not incident.
 *
 * `articleVector` should be the embedding of the article's title+summary
 * (or body). References are pre-normalized, so we normalize the article
 * vector here and use a dot product as cosine similarity.
 */
export function classifyByEmbedding(
  articleVector: number[],
  refs: Record<SubLabel, number[]>,
  threshold = 0.5,
): SubLabel[] {
  const a = normalize(articleVector);
  let best: SubLabel | null = null;
  let bestSim = -Infinity;
  for (const label of SUBCATEGORY_LABELS) {
    const sim = dot(a, refs[label]);
    if (sim > bestSim) { bestSim = sim; best = label; }
  }
  return best !== null && bestSim >= threshold ? [best] : [];
}

/* ---------- vector math (small, dependency-free) ------------------ */

function averageVectors(vectors: number[][]): number[] {
  const dims = vectors[0].length;
  const acc = new Array<number>(dims).fill(0);
  for (const v of vectors) {
    for (let i = 0; i < dims; i++) acc[i] += v[i];
  }
  for (let i = 0; i < dims; i++) acc[i] /= vectors.length;
  return acc;
}

function normalize(v: number[]): number[] {
  let norm = 0;
  for (const x of v) norm += x * x;
  norm = Math.sqrt(norm) || 1;
  return v.map(x => x / norm);
}

function dot(a: number[], b: number[]): number {
  let s = 0;
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) s += a[i] * b[i];
  return s;
}

/** Convenience: embed a single article text for subcategory classification. */
export async function embedForSubcategory(
  env: Env,
  cfg: RagConfig,
  title: string,
  summary: string,
): Promise<number[]> {
  const text = (title + " " + (summary || "")).trim();
  return embed(env, text, cfg);
}
