// lib/fetcher/technique-embed.ts
// ---------------------------------------------------------------------
// Embedding-based classification of AI attack TECHNIQUES, for the
// /ai-security page's trend chart. Same prototype-vector approach as
// lib/fetcher/subcategory-embed.ts (vulnerability/incident), but a
// separate label set and a separate rag_config key namespace so this
// never interacts with that classifier.
//
// Scope: only run this on articles that qualify for the AI×Security
// intersection (see AI_SECURITY_WHERE in app/ai-security/page.tsx) — most
// articles have nothing to do with AI attack techniques, so classifying
// everything would just produce noise (and cost).
//
// Expected accuracy: start modest (roughly 60-70%) with 4 broad,
// deliberately non-overlapping categories. Refine prototypes/threshold
// after seeing real misclassifications, same as vulnerability/incident
// needed a single-label fix after launch.
// ---------------------------------------------------------------------

import type { Env } from "../types";
import type { RagConfig } from "../rag/config";
import { embed, embedBatch } from "../rag/embeddings";

export const TECHNIQUE_LABELS = [
  "phishing-genai",  // generative-AI-written phishing/scam content
  "deepfake",        // voice/video deepfakes for fraud or impersonation
  "model-attack",    // attacks ON an AI model itself (prompt injection, data poisoning, model theft)
  "ai-automation",   // AI automating attacks (malware generation, auto vuln discovery)
] as const;
export type TechniqueLabel = typeof TECHNIQUE_LABELS[number];

export const TECHNIQUE_PROTOTYPES: Record<TechniqueLabel, string[]> = {
  "phishing-genai": [
    "Attackers used a generative AI chatbot to write convincing phishing emails at scale.",
    "Scammers used AI-generated text to craft fake business emails and social engineering lures.",
    "A large language model was used to automatically generate fraudulent messages targeting victims.",
    "生成AIを悪用してフィッシングメールや詐欺文面を大量に作成する手口が確認された。",
    "AIチャットボットが偽の問い合わせ対応や詐欺メッセージの作成に悪用された。",
  ],
  "deepfake": [
    "A deepfake video of a company executive was used to authorize a fraudulent wire transfer.",
    "Scammers used AI-cloned voice audio to impersonate a CEO during a phone call.",
    "A fake video generated by AI was used to spread disinformation or defraud victims.",
    "ディープフェイク音声を使い、経営者になりすまして送金を指示する詐欺が発生した。",
    "AIで生成した偽動画が詐欺や世論操作に悪用された。",
  ],
  "model-attack": [
    "Researchers demonstrated a prompt injection attack that manipulated an AI model's output.",
    "An AI model was poisoned with malicious training data to alter its behavior.",
    "Attackers attempted to steal or extract a proprietary machine learning model.",
    "プロンプトインジェクション攻撃により、AIモデルの出力を意図的に操作された。",
    "AIモデルへのデータポイズニングや不正な学習データ混入が確認された。",
  ],
  "ai-automation": [
    "Attackers used AI tools to automatically generate malware code.",
    "An AI system was used to automatically scan for and discover software vulnerabilities.",
    "Security researchers found that AI is being used to accelerate and automate cyberattacks.",
    "AIを使ってマルウェアのコードを自動生成する攻撃手法が報告された。",
    "AIが脆弱性の自動探索や攻撃の自動化に利用されている。",
  ],
};

const REF_KEY_PREFIX = "techref:"; // separate rag_config namespace from subref:

/** Generate + persist reference vectors for the technique labels. */
export async function generateTechniqueRefs(
  env: Env,
  cfg: RagConfig,
): Promise<{ label: TechniqueLabel; dims: number }[]> {
  const out: { label: TechniqueLabel; dims: number }[] = [];
  for (const label of TECHNIQUE_LABELS) {
    const vectors = await embedBatch(env, TECHNIQUE_PROTOTYPES[label], cfg);
    if (!vectors.length) continue;
    const ref = normalize(averageVectors(vectors));
    await env.DB.prepare(
      `INSERT INTO rag_config (key, value, updated_at)
       VALUES (?, ?, CURRENT_TIMESTAMP)
       ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP`
    ).bind(REF_KEY_PREFIX + label, JSON.stringify(ref)).run();
    out.push({ label, dims: ref.length });
  }
  return out;
}

/** Load stored technique reference vectors. Null if incomplete/absent. */
export async function loadTechniqueRefs(env: Env): Promise<Record<TechniqueLabel, number[]> | null> {
  const res = await env.DB.prepare(`SELECT key, value FROM rag_config WHERE key LIKE ?`)
    .bind(REF_KEY_PREFIX + "%").all();
  const map: Partial<Record<TechniqueLabel, number[]>> = {};
  for (const r of res.results ?? []) {
    const row = r as { key: string; value: string };
    const label = row.key.slice(REF_KEY_PREFIX.length) as TechniqueLabel;
    if ((TECHNIQUE_LABELS as readonly string[]).includes(label)) {
      try { map[label] = JSON.parse(row.value) as number[]; } catch { /* skip */ }
    }
  }
  const complete = TECHNIQUE_LABELS.every(l => Array.isArray(map[l]) && map[l]!.length);
  return complete ? (map as Record<TechniqueLabel, number[]>) : null;
}

/**
 * Single-label classification (highest cosine similarity, must clear
 * `threshold`), same rationale as vulnerability/incident: these categories
 * overlap in wording (e.g. an AI-automation article often also mentions
 * malware), so picking the dominant one avoids double-tagging noise.
 */
export function classifyTechnique(
  articleVector: number[],
  refs: Record<TechniqueLabel, number[]>,
  threshold = 0.5,
): TechniqueLabel[] {
  const a = normalize(articleVector);
  let best: TechniqueLabel | null = null;
  let bestSim = -Infinity;
  for (const label of TECHNIQUE_LABELS) {
    const sim = dot(a, refs[label]);
    if (sim > bestSim) { bestSim = sim; best = label; }
  }
  return best !== null && bestSim >= threshold ? [best] : [];
}

/* ---------- vector math (duplicated from subcategory-embed.ts on ------
   purpose — small, dependency-free, and keeps this module independent so
   changes to one classifier can't accidentally affect the other) ------ */

function averageVectors(vectors: number[][]): number[] {
  const dims = vectors[0].length;
  const acc = new Array<number>(dims).fill(0);
  for (const v of vectors) for (let i = 0; i < dims; i++) acc[i] += v[i];
  for (let i = 0; i < dims; i++) acc[i] /= vectors.length;
  return acc;
}

function normalize(v: number[]): number[] {
  let norm = 0;
  for (const x of v) norm += x * x;
  norm = Math.sqrt(norm) || 1;
  return v.map(x => x / norm);
}

function dot(a: number[], b: number[]): number {
  let s = 0;
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) s += a[i] * b[i];
  return s;
}

export async function embedForTechnique(
  env: Env,
  cfg: RagConfig,
  title: string,
  summary: string,
): Promise<number[]> {
  const text = (title + " " + (summary || "")).trim();
  return embed(env, text, cfg);
}
